services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quiz-network

  api:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - quiz-network
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/target
    env_file:
      - ./api/.env

  web:
    build: ./web
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - quiz-network
    env_file:
      - ./web/.env

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres-data:
