services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quiz-network

  api:
    build: ./api
    networks:
      - quiz-network
    depends_on:
      - db
    env_file:
      - ./api/.env

  web:
    build: ./web
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - quiz-network
    env_file:
      - ./web/.env

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres-data:
